[Global]
epoch=30
batch_size=30
grad_norm=1.0
early_stopping={metric='acc',patience=5}


[[Fields]]
class = "text"
    [Fields.init]
    name = "text"
    [Fields.init.tokenizer]
    path="data/electra_base"

[[Fields]]
class = "sequence"
    [Fields.init]
    name = "pos"
    unk = false
    is_target = true
    pad_bias = true

[Dataset]
class = "line"
path="data/ltp-data/pos"
train="train.txt"
validation="valid.txt"
test="test.txt"
    [Dataset.init]
    split='_'

[[Metrics]]
class = "Accuracy"
    [Metrics.init]
    pad_value = -1

[Loss]
class = "CrossEntropyLoss"
    [Loss.init]
    ignore_index=-1

[Optimizer]
class = "Adam"
    [Optimizer.init]
    lr = 1e-4

[Scheduler]
class = "LinearLRW"
type = 'step'
warmup_proportion=0.002

[Predictor]
class = "simple"

[Checkpoint]
directory="checkpoint/ltp_base/pos"
plugins=['best','restore']
best={ metric='acc' }

[Model]
class = "SimpleTagging"

    [Model.init]
    label_num=27
    word_base=true
    pretrained="data/electra_base"

